UC1:Data Ingestion

In [2]:
import pandas as pd

In [8]:
deliveries_df = pd.read_csv(r"C:\Users\hpat3221\OneDrive - 7-Eleven, Inc\Desktop\Development\PandaTraining\data\deliveries.csv")
matches_df = pd.read_csv(r"C:\Users\hpat3221\OneDrive - 7-Eleven, Inc\Desktop\Development\PandaTraining\data\matches .csv")

In [9]:
print("DELIVERIES DATAFRAME")

# Shape
print("Shape:", deliveries_df.shape)

# Columns
print("Columns:", deliveries_df.columns.tolist())

# Data Types
print("Data Types:\n", deliveries_df.dtypes)

DELIVERIES DATAFRAME
Shape: (260920, 17)
Columns: ['match_id', 'inning', 'batting_team', 'bowling_team', 'over', 'ball', 'batter', 'bowler', 'non_striker', 'batsman_runs', 'extra_runs', 'total_runs', 'extras_type', 'is_wicket', 'player_dismissed', 'dismissal_kind', 'fielder']
Data Types:
 match_id            int64
inning              int64
batting_team          str
bowling_team          str
over                int64
ball                int64
batter                str
bowler                str
non_striker           str
batsman_runs        int64
extra_runs          int64
total_runs          int64
extras_type           str
is_wicket           int64
player_dismissed      str
dismissal_kind        str
fielder               str
dtype: object

In [10]:
print("\nMATCHES DATAFRAME")

# Shape
print("Shape:", matches_df.shape)

# Columns
print("Columns:", matches_df.columns.tolist())

# Data Types
print("Data Types:\n", matches_df.dtypes)

MATCHES DATAFRAME
Shape: (1095, 20)
Columns: ['id', 'season', 'city', 'date', 'match_type', 'player_of_match', 'venue', 'team1', 'team2', 'toss_winner', 'toss_decision', 'winner', 'result', 'result_margin', 'target_runs', 'target_overs', 'super_over', 'method', 'umpire1', 'umpire2']
Data Types:
 id                   int64
season                 str
city                   str
date                   str
match_type             str
player_of_match        str
venue                  str
team1                  str
team2                  str
toss_winner            str
toss_decision          str
winner                 str
result                 str
result_margin      float64
target_runs        float64
target_overs       float64
super_over             str
method                 str
umpire1                str
umpire2                str
dtype: object

UC2:DATA CLEANING AND VALIDATION

Step 1: Check for Missing Values

In [11]:
# Check missing values

print("===== MISSING VALUES: DELIVERIES =====")
print(deliveries_df.isnull().sum())

print("\n===== MISSING VALUES: MATCHES =====")
print(matches_df.isnull().sum())

===== MISSING VALUES: DELIVERIES =====
match_id                 0
inning                   0
batting_team             0
bowling_team             0
over                     0
ball                     0
batter                   0
bowler                   0
non_striker              0
batsman_runs             0
extra_runs               0
total_runs               0
extras_type         246795
is_wicket                0
player_dismissed    247970
dismissal_kind      247970
fielder             251566
dtype: int64

===== MISSING VALUES: MATCHES =====
id                    0
season                0
city                 51
date                  0
match_type            0
player_of_match       5
venue                 0
team1                 0
team2                 0
toss_winner           0
toss_decision         0
winner                5
result                0
result_margin        19
target_runs           3
target_overs          3
super_over            0
method             1074
umpire1               0
umpire2               0
dtype: int64

Step 2: Handle / Report Inconsistencies

In [15]:
# Create copies
deliveries_df_cleaned = deliveries_df.copy()
matches_df_cleaned = matches_df.copy()

# Handle missing values (correct way)

matches_df_cleaned['winner'] = matches_df_cleaned['winner'].fillna('Unknown')
matches_df_cleaned['player_of_match'] = matches_df_cleaned['player_of_match'].fillna('Unknown')
matches_df_cleaned['city'] = matches_df_cleaned['city'].fillna('Unknown')

print("Missing values handled for key columns")

Missing values handled for key columns

Step 3: Validation (IDs + Data Types)

In [16]:


deliveries_df_cleaned['match_id'] = deliveries_df_cleaned['match_id'].astype(int)
matches_df_cleaned['id'] = matches_df_cleaned['id'].astype(int)

print("Data types validated successfully")



delivery_ids = set(deliveries_df_cleaned['match_id'].unique())
match_ids = set(matches_df_cleaned['id'].unique())

missing_ids = delivery_ids - match_ids

if len(missing_ids) == 0:
    print("All match IDs are consistent between datasets")
else:
    print(f"Inconsistency found: {len(missing_ids)} match_ids missing in matches dataset")

Data types validated successfully
All match IDs are consistent between datasets

Step 1: Create New Column (Total Runs per Ball)

In [17]:


deliveries_df_cleaned['total_runs'] = (
    deliveries_df_cleaned['batsman_runs'] +
    deliveries_df_cleaned['extra_runs']
)

print("total_runs column created successfully")
deliveries_df_cleaned[['batsman_runs', 'extra_runs', 'total_runs']].head()

total_runs column created successfully

   batsman_runs  extra_runs  total_runs
0             0           1           1
1             0           0           0
2             0           1           1
3             0           0           0
4             0           0           0

Step 2: Standardize Column Names

In [18]:


deliveries_df_cleaned.columns = deliveries_df_cleaned.columns.str.lower().str.strip()
matches_df_cleaned.columns = matches_df_cleaned.columns.str.lower().str.strip()

print("Column names standardized")
print(deliveries_df_cleaned.columns)
print(matches_df_cleaned.columns)

Column names standardized
Index(['match_id', 'inning', 'batting_team', 'bowling_team', 'over', 'ball',
       'batter', 'bowler', 'non_striker', 'batsman_runs', 'extra_runs',
       'total_runs', 'extras_type', 'is_wicket', 'player_dismissed',
       'dismissal_kind', 'fielder'],
      dtype='str')
Index(['id', 'season', 'city', 'date', 'match_type', 'player_of_match',
       'venue', 'team1', 'team2', 'toss_winner', 'toss_decision', 'winner',
       'result', 'result_margin', 'target_runs', 'target_overs', 'super_over',
       'method', 'umpire1', 'umpire2'],
      dtype='str')

Step 3: Merge Datasets

In [19]:


ipl_df = deliveries_df_cleaned.merge(
    matches_df_cleaned,
    left_on="match_id",
    right_on="id",
    how="inner"
)

print("Datasets merged successfully")

# Final output
print("\nUnified DataFrame ready for analysis")
print("Shape:", ipl_df.shape)

ipl_df.head()

Datasets merged successfully

Unified DataFrame ready for analysis
Shape: (260920, 37)

,match_id,inning,batting_team,bowling_team,over,ball,batter,bowler,non_striker,batsman_runs,...,toss_decision,winner,result,result_margin,target_runs,target_overs,super_over,method,umpire1,umpire2
0,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,1,SC Ganguly,P Kumar,BB McCullum,0,...,field,Kolkata Knight Riders,runs,140.0,223.0,20.0,N,NaN,Asad Rauf,RE Koertzen
1,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,2,BB McCullum,P Kumar,SC Ganguly,0,...,field,Kolkata Knight Riders,runs,140.0,223.0,20.0,N,NaN,Asad Rauf,RE Koertzen
2,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,3,BB McCullum,P Kumar,SC Ganguly,0,...,field,Kolkata Knight Riders,runs,140.0,223.0,20.0,N,NaN,Asad Rauf,RE Koertzen
3,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,4,BB McCullum,P Kumar,SC Ganguly,0,...,field,Kolkata Knight Riders,runs,140.0,223.0,20.0,N,NaN,Asad Rauf,RE Koertzen
4,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,5,BB McCullum,P Kumar,SC Ganguly,0,...,field,Kolkata Knight Riders,runs,140.0,223.0,20.0,N,NaN,Asad Rauf,RE Koertzen