UC1:Data Ingestion

In [2]:
import pandas as pd

In [8]:
deliveries_df = pd.read_csv(r"C:\Users\hpat3221\OneDrive - 7-Eleven, Inc\Desktop\Development\PandaTraining\data\deliveries.csv")
matches_df = pd.read_csv(r"C:\Users\hpat3221\OneDrive - 7-Eleven, Inc\Desktop\Development\PandaTraining\data\matches .csv")

In [9]:
print("DELIVERIES DATAFRAME")

# Shape
print("Shape:", deliveries_df.shape)

# Columns
print("Columns:", deliveries_df.columns.tolist())

# Data Types
print("Data Types:\n", deliveries_df.dtypes)

DELIVERIES DATAFRAME
Shape: (260920, 17)
Columns: ['match_id', 'inning', 'batting_team', 'bowling_team', 'over', 'ball', 'batter', 'bowler', 'non_striker', 'batsman_runs', 'extra_runs', 'total_runs', 'extras_type', 'is_wicket', 'player_dismissed', 'dismissal_kind', 'fielder']
Data Types:
 match_id            int64
inning              int64
batting_team          str
bowling_team          str
over                int64
ball                int64
batter                str
bowler                str
non_striker           str
batsman_runs        int64
extra_runs          int64
total_runs          int64
extras_type           str
is_wicket           int64
player_dismissed      str
dismissal_kind        str
fielder               str
dtype: object

In [10]:
print("\nMATCHES DATAFRAME")

# Shape
print("Shape:", matches_df.shape)

# Columns
print("Columns:", matches_df.columns.tolist())

# Data Types
print("Data Types:\n", matches_df.dtypes)

MATCHES DATAFRAME
Shape: (1095, 20)
Columns: ['id', 'season', 'city', 'date', 'match_type', 'player_of_match', 'venue', 'team1', 'team2', 'toss_winner', 'toss_decision', 'winner', 'result', 'result_margin', 'target_runs', 'target_overs', 'super_over', 'method', 'umpire1', 'umpire2']
Data Types:
 id                   int64
season                 str
city                   str
date                   str
match_type             str
player_of_match        str
venue                  str
team1                  str
team2                  str
toss_winner            str
toss_decision          str
winner                 str
result                 str
result_margin      float64
target_runs        float64
target_overs       float64
super_over             str
method                 str
umpire1                str
umpire2                str
dtype: object

UC2:DATA CLEANING AND VALIDATION

Step 1: Check for Missing Values

In [11]:
# Check missing values

print("===== MISSING VALUES: DELIVERIES =====")
print(deliveries_df.isnull().sum())

print("\n===== MISSING VALUES: MATCHES =====")
print(matches_df.isnull().sum())

===== MISSING VALUES: DELIVERIES =====
match_id                 0
inning                   0
batting_team             0
bowling_team             0
over                     0
ball                     0
batter                   0
bowler                   0
non_striker              0
batsman_runs             0
extra_runs               0
total_runs               0
extras_type         246795
is_wicket                0
player_dismissed    247970
dismissal_kind      247970
fielder             251566
dtype: int64

===== MISSING VALUES: MATCHES =====
id                    0
season                0
city                 51
date                  0
match_type            0
player_of_match       5
venue                 0
team1                 0
team2                 0
toss_winner           0
toss_decision         0
winner                5
result                0
result_margin        19
target_runs           3
target_overs          3
super_over            0
method             1074
umpire1               0
umpire2               0
dtype: int64

Step 2: Handle / Report Inconsistencies

In [15]:
# Create copies
deliveries_df_cleaned = deliveries_df.copy()
matches_df_cleaned = matches_df.copy()

# Handle missing values (correct way)

matches_df_cleaned['winner'] = matches_df_cleaned['winner'].fillna('Unknown')
matches_df_cleaned['player_of_match'] = matches_df_cleaned['player_of_match'].fillna('Unknown')
matches_df_cleaned['city'] = matches_df_cleaned['city'].fillna('Unknown')

print("Missing values handled for key columns")

Missing values handled for key columns

Step 3: Validation (IDs + Data Types)

In [16]:


deliveries_df_cleaned['match_id'] = deliveries_df_cleaned['match_id'].astype(int)
matches_df_cleaned['id'] = matches_df_cleaned['id'].astype(int)

print("Data types validated successfully")



delivery_ids = set(deliveries_df_cleaned['match_id'].unique())
match_ids = set(matches_df_cleaned['id'].unique())

missing_ids = delivery_ids - match_ids

if len(missing_ids) == 0:
    print("All match IDs are consistent between datasets")
else:
    print(f"Inconsistency found: {len(missing_ids)} match_ids missing in matches dataset")

Data types validated successfully
All match IDs are consistent between datasets

Step 1: Create New Column (Total Runs per Ball)

In [17]:


deliveries_df_cleaned['total_runs'] = (
    deliveries_df_cleaned['batsman_runs'] +
    deliveries_df_cleaned['extra_runs']
)

print("total_runs column created successfully")
deliveries_df_cleaned[['batsman_runs', 'extra_runs', 'total_runs']].head()

total_runs column created successfully

   batsman_runs  extra_runs  total_runs
0             0           1           1
1             0           0           0
2             0           1           1
3             0           0           0
4             0           0           0

Step 2: Standardize Column Names

In [18]:


deliveries_df_cleaned.columns = deliveries_df_cleaned.columns.str.lower().str.strip()
matches_df_cleaned.columns = matches_df_cleaned.columns.str.lower().str.strip()

print("Column names standardized")
print(deliveries_df_cleaned.columns)
print(matches_df_cleaned.columns)

Column names standardized
Index(['match_id', 'inning', 'batting_team', 'bowling_team', 'over', 'ball',
       'batter', 'bowler', 'non_striker', 'batsman_runs', 'extra_runs',
       'total_runs', 'extras_type', 'is_wicket', 'player_dismissed',
       'dismissal_kind', 'fielder'],
      dtype='str')
Index(['id', 'season', 'city', 'date', 'match_type', 'player_of_match',
       'venue', 'team1', 'team2', 'toss_winner', 'toss_decision', 'winner',
       'result', 'result_margin', 'target_runs', 'target_overs', 'super_over',
       'method', 'umpire1', 'umpire2'],
      dtype='str')

Step 3: Merge Datasets

In [19]:


ipl_df = deliveries_df_cleaned.merge(
    matches_df_cleaned,
    left_on="match_id",
    right_on="id",
    how="inner"
)

print("Datasets merged successfully")

# Final output
print("\nUnified DataFrame ready for analysis")
print("Shape:", ipl_df.shape)

ipl_df.head()

Datasets merged successfully

Unified DataFrame ready for analysis
Shape: (260920, 37)

,match_id,inning,batting_team,bowling_team,over,ball,batter,bowler,non_striker,batsman_runs,...,toss_decision,winner,result,result_margin,target_runs,target_overs,super_over,method,umpire1,umpire2
0,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,1,SC Ganguly,P Kumar,BB McCullum,0,...,field,Kolkata Knight Riders,runs,140.0,223.0,20.0,N,NaN,Asad Rauf,RE Koertzen
1,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,2,BB McCullum,P Kumar,SC Ganguly,0,...,field,Kolkata Knight Riders,runs,140.0,223.0,20.0,N,NaN,Asad Rauf,RE Koertzen
2,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,3,BB McCullum,P Kumar,SC Ganguly,0,...,field,Kolkata Knight Riders,runs,140.0,223.0,20.0,N,NaN,Asad Rauf,RE Koertzen
3,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,4,BB McCullum,P Kumar,SC Ganguly,0,...,field,Kolkata Knight Riders,runs,140.0,223.0,20.0,N,NaN,Asad Rauf,RE Koertzen
4,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,5,BB McCullum,P Kumar,SC Ganguly,0,...,field,Kolkata Knight Riders,runs,140.0,223.0,20.0,N,NaN,Asad Rauf,RE Koertzen

UC4:SCORE ANALYSIS

Step 1:Total Runs per Match

In [20]:
total_runs_per_match = ipl_df.groupby('match_id')['total_runs'].sum().reset_index()
total_runs_per_match.columns = ['match_id', 'total_runs']

total_runs_per_match.head()

   match_id  total_runs
0    335982         304
1    335983         447
2    335984         261
3    335985         331
4    335986         222

Step 2:Runs per Team per Match

In [ ]:
runs_per_team_match = ipl_df.groupby(['match_id', 'batting_team'])['total_runs'].sum().reset_index()

runs_per_team_match.head()

Step 3:Top 10 Batters

In [21]:
top_batters = ipl_df.groupby('batter')['batsman_runs'].sum().sort_values(ascending=False).head(10)

top_batters

batter
V Kohli           8014
S Dhawan          6769
RG Sharma         6630
DA Warner         6567
SK Raina          5536
MS Dhoni          5243
AB de Villiers    5181
CH Gayle          4997
RV Uthappa        4954
KD Karthik        4843
Name: batsman_runs, dtype: int64

Step 4:Strike Rate of Batters

In [22]:
batters_stats = ipl_df.groupby('batter').agg(
    runs=('batsman_runs', 'sum'),
    balls=('batsman_runs', 'count')
).reset_index()

batters_stats['strike_rate'] = (batters_stats['runs'] / batters_stats['balls']) * 100

batters_stats.sort_values(by='strike_rate', ascending=False).head(10)

              batter  runs  balls  strike_rate
312           L Wood     9      3   300.000000
97        B Stanlake     5      2   250.000000
234  J Fraser-McGurk   330    150   220.000000
461    R Sai Kishore    13      6   216.666667
629         Umar Gul    39     19   205.263158
497         RS Sodhi     4      2   200.000000
583    Shahid Afridi    81     46   176.086957
222       I Malhotra     7      4   175.000000
652         WG Jacks   230    133   172.932331
433          PD Salt   653    385   169.610390

Step 5:Top 10 bowlers by economy

In [23]:
bowler_stats = ipl_df.groupby('bowler').agg(
    runs=('total_runs', 'sum'),
    balls=('bowler', 'count')
).reset_index()

bowler_stats['overs'] = bowler_stats['balls'] / 6
bowler_stats['economy'] = bowler_stats['runs'] / bowler_stats['overs']

bowler_stats.sort_values(by='economy').head(10)

            bowler  runs  balls     overs   economy
24    AC Gilchrist     0      1  0.166667  0.000000
364     R Ravindra     7     12  2.000000  3.500000
317       NB Singh    18     25  4.166667  4.320000
460    Sachin Baby     8     10  1.666667  4.800000
38       AM Rahane     5      6  1.000000  5.000000
245  LA Carseldine     6      7  1.166667  5.142857
453      SS Mundhe     6      7  1.166667  5.142857
125    DJ Thornely    40     44  7.333333  5.454545
260       M Manhas    42     42  7.000000  6.000000
296       MW Short    25     25  4.166667  6.000000

Step 6:Most Consistent Batters

In [24]:
consistency = ipl_df.groupby(['batter', 'match_id'])['batsman_runs'].sum().reset_index()

consistency_stats = consistency.groupby('batter').agg(
    avg_runs=('batsman_runs', 'mean'),
    matches=('match_id', 'count')
).reset_index()

consistent_batters = consistency_stats[
    consistency_stats['matches'] >= 10
].sort_values(by='avg_runs', ascending=False)

consistent_batters.head(10)

              batter   avg_runs  matches
170        DP Conway  42.000000       22
96   B Sai Sudharsan  41.360000       25
289         KL Rahul  38.434426      122
319      LMP Simmons  37.206897       29
473       RD Gaikwad  36.615385       65
542         SE Marsh  36.072464       69
214          HM Amla  36.062500       16
147        DA Warner  35.690217      184
124         CH Gayle  35.439716      141
365        ML Hayden  34.593750       32

Step 7:Highest Individual score in a match

In [25]:
highest_score = ipl_df.groupby(['match_id', 'batter'])['batsman_runs'].sum().reset_index()

highest_score.sort_values(by='batsman_runs', ascending=False).head(1)

      match_id    batter  batsman_runs
5302    598027  CH Gayle           175

Step 8:Boundary Analysis

In [26]:
boundaries = ipl_df[ipl_df['batsman_runs'].isin([4, 6])]

boundary_counts = boundaries.groupby('batter')['batsman_runs'].count().sort_values(ascending=False)

boundary_counts.head(10)

batter
V Kohli           981
S Dhawan          921
DA Warner         899
RG Sharma         880
CH Gayle          767
SK Raina          710
AB de Villiers    667
RV Uthappa        663
KD Karthik        627
MS Dhoni          615
Name: batsman_runs, dtype: int64

Step 9:Boundary Percentage

In [27]:
batter_total = ipl_df.groupby('batter')['batsman_runs'].sum()
batter_boundaries = ipl_df[ipl_df['batsman_runs'].isin([4, 6])].groupby('batter')['batsman_runs'].sum()

boundary_percent = (batter_boundaries / batter_total) * 100

boundary_percent.sort_values(ascending=False).head(10)

batter
P Chopra           100.000000
GD McGrath         100.000000
VRV Singh          100.000000
A Tomar            100.000000
RS Sodhi           100.000000
BA Bhatt           100.000000
Liton Das          100.000000
R Sai Kishore       92.307692
J Fraser-McGurk     89.696970
AA Kulkarni         88.888889
Name: batsman_runs, dtype: float64

Step 10:Dot Ball Analysis

In [28]:
dot_balls = ipl_df[ipl_df['batsman_runs'] == 0]

dot_count = dot_balls.groupby('bowler')['batsman_runs'].count().sort_values(ascending=False)

dot_count.head(10)

bowler
B Kumar            1872
R Ashwin           1758
SP Narine          1694
PP Chawla          1402
JJ Bumrah          1391
Harbhajan Singh    1390
UT Yadav           1381
SL Malinga         1357
YS Chahal          1349
RA Jadeja          1324
Name: batsman_runs, dtype: int64

Step 11:Runs per Over Analysis

In [37]:
runs_per_over = ipl_df.groupby('over')['total_runs'].mean().reset_index()

runs_per_over.columns = ['over', 'avg_runs']

runs_per_over

    over  avg_runs
0      0  0.981663
1      1  1.173528
2      2  1.316099
3      3  1.356538
4      4  1.369100
5      5  1.373055
6      6  1.103107
7      7  1.189948
8      8  1.242087
9      9  1.224577
10    10  1.262623
11    11  1.287686
12    12  1.301240
13    13  1.343645
14    14  1.393504
15    15  1.434273
16    16  1.498778
17    17  1.587839
18    18  1.646896
19    19  1.776855

Step 12:Powerplay(1-6 overs)

In [29]:
powerplay = ipl_df[ipl_df['over'] <= 6]

powerplay_runs = powerplay.groupby('batting_team')['total_runs'].sum().sort_values(ascending=False)

powerplay_runs

batting_team
Mumbai Indians                 13943
Kolkata Knight Riders          13632
Chennai Super Kings            12631
Royal Challengers Bangalore    12429
Rajasthan Royals               11774
Kings XI Punjab                10295
Sunrisers Hyderabad            10170
Delhi Daredevils                8503
Delhi Capitals                  5358
Deccan Chargers                 3889
Punjab Kings                    3231
Gujarat Titans                  2504
Lucknow Super Giants            2355
Pune Warriors                   2141
Gujarat Lions                   1818
Royal Challengers Bengaluru      993
Rising Pune Supergiant           877
Kochi Tuskers Kerala             769
Rising Pune Supergiants          744
Name: total_runs, dtype: int64

Step 13:Death overs

In [30]:
death_overs = ipl_df[(ipl_df['over'] >= 16) & (ipl_df['over'] <= 20)]

death_runs = death_overs.groupby('batting_team')['total_runs'].sum().sort_values(ascending=False)

death_runs

batting_team
Mumbai Indians                 9598
Chennai Super Kings            9061
Royal Challengers Bangalore    8417
Kolkata Knight Riders          8053
Rajasthan Royals               7281
Sunrisers Hyderabad            6237
Kings XI Punjab                6227
Delhi Daredevils               5043
Delhi Capitals                 3141
Deccan Chargers                2539
Punjab Kings                   2047
Gujarat Titans                 1823
Lucknow Super Giants           1718
Pune Warriors                  1360
Gujarat Lions                   921
Royal Challengers Bengaluru     611
Rising Pune Supergiant          555
Rising Pune Supergiants         443
Kochi Tuskers Kerala            337
Name: total_runs, dtype: int64

Step 14:Run Distribution per Inning

In [31]:
inning_runs = ipl_df.groupby('inning')['total_runs'].sum()

inning_runs

inning
1    181274
2    166196
3       137
4       123
5        11
6        15
Name: total_runs, dtype: int64

Step 15:Toss Impact Analysis

In [32]:
toss_runs = ipl_df.groupby('toss_winner')['total_runs'].sum().sort_values(ascending=False)

toss_runs

toss_winner
Mumbai Indians                 46198
Chennai Super Kings            38169
Rajasthan Royals               38056
Kolkata Knight Riders          37990
Royal Challengers Bangalore    35326
Sunrisers Hyderabad            27420
Kings XI Punjab                27298
Delhi Daredevils               24412
Delhi Capitals                 16429
Deccan Chargers                13417
Punjab Kings                    8511
Gujarat Titans                  7661
Lucknow Super Giants            7019
Pune Warriors                   5824
Gujarat Lions                   5003
Royal Challengers Bengaluru     3111
Kochi Tuskers Kerala            2186
Rising Pune Supergiants         1895
Rising Pune Supergiant          1831
Name: total_runs, dtype: int64

Step 16:Player of the Match Contribution

In [33]:
pom_runs = ipl_df.groupby(['match_id', 'player_of_match', 'batter'])['batsman_runs'].sum().reset_index()

pom_runs.head()

   match_id player_of_match       batter  batsman_runs
0    335982     BB McCullum    AA Noffke             9
1    335982     BB McCullum      B Akhil             0
2    335982     BB McCullum  BB McCullum           158
3    335982     BB McCullum     CL White             6
4    335982     BB McCullum    DJ Hussey            12

Step 17:Venue-wise Analysis

In [34]:
venue_runs = ipl_df.groupby('venue')['total_runs'].mean().sort_values(ascending=False)

venue_runs

venue
Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket Stadium, Visakhapatnam       1.600000
Eden Gardens, Kolkata                                                    1.577242
M Chinnaswamy Stadium, Bengaluru                                         1.554777
Himachal Pradesh Cricket Association Stadium, Dharamsala                 1.542770
Punjab Cricket Association IS Bindra Stadium, Mohali, Chandigarh         1.537697
Arun Jaitley Stadium, Delhi                                              1.536967
Rajiv Gandhi International Stadium, Uppal, Hyderabad                     1.509548
M.Chinnaswamy Stadium                                                    1.467373
Holkar Cricket Stadium                                                   1.461578
Sawai Mansingh Stadium, Jaipur                                           1.443460
Narendra Modi Stadium, Ahmedabad                                         1.439929
Brabourne Stadium, Mumbai                                                1.435544
Punjab Cricket Association IS Bindra Stadium                             1.431042
Wankhede Stadium, Mumbai                                                 1.428035
Brabourne Stadium                                                        1.409883
Green Park                                                               1.409338
Saurashtra Cricket Association Stadium                                   1.399832
Barsapara Cricket Stadium, Guwahati                                      1.378890
Punjab Cricket Association IS Bindra Stadium, Mohali                     1.377234
M Chinnaswamy Stadium                                                    1.359294
Maharaja Yadavindra Singh International Cricket Stadium, Mullanpur       1.356275
Arun Jaitley Stadium                                                     1.353695
Barabati Stadium                                                         1.343953
Himachal Pradesh Cricket Association Stadium                             1.341825
Dr DY Patil Sports Academy, Mumbai                                       1.340061
Wankhede Stadium                                                         1.330624
Punjab Cricket Association Stadium, Mohali                               1.329180
Maharashtra Cricket Association Stadium                                  1.323574
Zayed Cricket Stadium, Abu Dhabi                                         1.320704
Feroz Shah Kotla                                                         1.320502
Maharashtra Cricket Association Stadium, Pune                            1.316667
Eden Gardens                                                             1.315210
Bharat Ratna Shri Atal Bihari Vajpayee Ekana Cricket Stadium, Lucknow    1.307950
Sardar Patel Stadium, Motera                                             1.302109
MA Chidambaram Stadium, Chepauk, Chennai                                 1.300763
MA Chidambaram Stadium, Chepauk                                          1.299065
Dubai International Cricket Stadium                                      1.286847
Sharjah Cricket Stadium                                                  1.286421
Rajiv Gandhi International Stadium                                       1.283181
Rajiv Gandhi International Stadium, Uppal                                1.283006
Sawai Mansingh Stadium                                                   1.279283
Sheikh Zayed Stadium                                                     1.278989
SuperSport Park                                                          1.274599
De Beers Diamond Oval                                                    1.235537
Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket Stadium                      1.233454
JSCA International Stadium Complex                                       1.230401
Shaheed Veer Narayan Singh International Stadium                         1.216632
St George's Park                                                         1.212284
Dr DY Patil Sports Academy                                               1.204608
MA Chidambaram Stadium                                                   1.203286
Kingsmead                                                                1.194894
Vidarbha Cricket Association Stadium, Jamtha                             1.188679
Subrata Roy Sahara Stadium                                               1.183791
New Wanderers Stadium                                                    1.181443
Nehru Stadium                                                            1.180087
Newlands                                                                 1.167641
Buffalo Park                                                             1.117483
OUTsurance Oval                                                          1.058000
Name: total_runs, dtype: float64

Step 18:City-wise Scoring Trends

In [35]:
city_runs = ipl_df.groupby('city')['total_runs'].mean().sort_values(ascending=False)

city_runs

city
Bengaluru         1.510626
Indore            1.461578
Kanpur            1.409338
Dharamsala        1.404648
Rajkot            1.399832
Ahmedabad         1.393312
Guwahati          1.378890
Chandigarh        1.372202
Delhi             1.366073
Kolkata           1.361485
Mumbai            1.361147
Bangalore         1.359294
Mohali            1.356275
Cuttack           1.343953
Hyderabad         1.321820
Unknown           1.321691
Navi Mumbai       1.309415
Jaipur            1.308062
Lucknow           1.307950
Chennai           1.289771
Abu Dhabi         1.287874
Visakhapatnam     1.285270
Pune              1.278127
Centurion         1.274599
Dubai             1.266751
Kimberley         1.235537
Ranchi            1.230401
Raipur            1.216632
Port Elizabeth    1.212284
Durban            1.194894
Nagpur            1.188679
Johannesburg      1.181443
Kochi             1.180087
Cape Town         1.167641
Sharjah           1.129087
East London       1.117483
Bloemfontein      1.058000
Name: total_runs, dtype: float64

Step 19:Season-wise Run Trends

In [38]:
season_runs = ipl_df.groupby('season')['total_runs'].sum().reset_index()

season_runs

     season  total_runs
0   2007/08       17937
1      2009       16353
2   2009/10       18883
3      2011       21154
4      2012       22453
5      2013       22602
6      2014       18931
7      2015       18353
8      2016       18862
9      2017       18786
10     2018       19901
11     2019       19434
12  2020/21       19416
13     2021       18637
14     2022       24395
15     2023       25688
16     2024       25971

Step 20:Winning Team Analysis

In [36]:
match_scores = ipl_df.groupby(['match_id', 'batting_team'])['total_runs'].sum().reset_index()

winner_analysis = match_scores.loc[match_scores.groupby('match_id')['total_runs'].idxmax()]

winner_analysis.head()

   match_id                 batting_team  total_runs
0    335982        Kolkata Knight Riders         222
2    335983          Chennai Super Kings         240
4    335984             Delhi Daredevils         132
7    335985  Royal Challengers Bangalore         166
9    335986        Kolkata Knight Riders         112

Step 1:Most Consistent Batter

In [ ]:

batter_match_runs = ipl_df.groupby(['batter', 'match_id'])['batsman_runs'].sum().reset_index()


batter_consistency = batter_match_runs.groupby('batter').agg(
    avg_runs=('batsman_runs', 'mean'),
    matches=('match_id', 'count')
).reset_index()

consistent_batters = batter_consistency[batter_consistency['matches'] >= 10]


most_consistent_batter = consistent_batters.sort_values(by='avg_runs', ascending=False).head(1)

most_consistent_batter

Step 2:Best Death-Over Team & High-Scoring Venues

In [ ]:


death_overs = ipl_df[(ipl_df['over'] >= 16) & (ipl_df['over'] <= 20)]

death_team_runs = death_overs.groupby('batting_team')['total_runs'].sum().reset_index()

best_death_team = death_team_runs.sort_values(by='total_runs', ascending=False).head(1)




venue_runs = ipl_df.groupby('venue')['total_runs'].mean().reset_index()

high_scoring_venue = venue_runs.sort_values(by='total_runs', ascending=False).head(1)


print("Best Death-Over Team:")
display(best_death_team)

print("\nHigh Scoring Venue:")
display(high_scoring_venue)

Step 3: Text-Based Insights

In [ ]:


batter_name = most_consistent_batter.iloc[0]['batter']
avg_runs = most_consistent_batter.iloc[0]['avg_runs']

team_name = best_death_team.iloc[0]['batting_team']
death_runs = best_death_team.iloc[0]['total_runs']

venue_name = high_scoring_venue.iloc[0]['venue']
venue_avg = high_scoring_venue.iloc[0]['total_runs']


print(" INSIGHTS \n")

print(f"1. Most Consistent Batter: {batter_name} with an average of {avg_runs:.2f} runs per match.")

print(f"2. Best Death-Over Team: {team_name} scored the highest runs ({death_runs}) in overs 16–20.")

print(f"3. High-Scoring Venue: {venue_name} has the highest average runs ({venue_avg:.2f}) per match.")